import "./styles/global.scss";
import {routing} from "@/i18n/routing";
import {SiteNavigationProvider} from "@/components/providers/site-navigation-provider";
import {ThemeProvider} from "@/components/providers/theme-provider";
import {PageTransitionProvider} from "@/components/TransitionLink";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang={routing.defaultLocale ?? 'en'}>
        <body style={{overflowX: 'hidden'}}>
        <ThemeProvider>
            <PageTransitionProvider>
                <SiteNavigationProvider>
                    {children}
                </SiteNavigationProvider>
            </PageTransitionProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
