import "./styles/global.scss";
import {routing} from "@/i18n/routing";
import {SiteNavigationProvider} from "@/components/providers/site-navigation-provider";

import {ThemeProvider} from "@/components/providers/theme-provider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {
    "use client"

    return (
        <html lang={routing.defaultLocale ?? 'en'}>
        <body>
        <ThemeProvider>
            <SiteNavigationProvider>
                {children}
            </SiteNavigationProvider>
        </ThemeProvider>
        </body>
        </html>
    )
}
